language: php
php:
  - 5.6
install:
  - composer install --no-dev
script:
  - phpunit --bootstrap=tests/backend/bootstrap.php --log-junit=tests/logs/test-result.xml --report-useless-tests tests/
services:
  - mysql
notifications:
  email : false
