language: php
php:
  - 7.2
  - 5.6
install:
  - mysql < setuptestdb.sql
  - composer install
script:
  - vendor/bin/phpunit --log-junit=tests/logs/test-result.xml --report-useless-tests tests/
services:
  - mysql
notifications:
  email : false
